### ISSUE TITLE
Implement ReplicationFilterCompiler and ReplicationFilter

### ISSUE THREAD

**Issue by tinderangler** [couchbase/couchbase-lite-java-javascript#11]
Would be great if you could also implement ReplicationFilterCompiler.

**Comment by hideki** [comment]
Current temporary solution. 
- https://github.com/couchbase/couchbase-lite-java-javascript/blob/demo/filetercompiler/src/main/java/com/couchbase/lite/javascript/JavaScriptReplicationFilter.java
- https://github.com/couchbase/couchbase-lite-java-javascript/blob/demo/filetercompiler/src/main/java/com/couchbase/lite/javascript/JavaScriptReplicationFilterCompiler.java

**Comment by hideki** [comment]
Needs to update PhoneGap Plugin to enable FilterCompiler
https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/62
