### ISSUE TITLE
sum function not working

### ISSUE THREAD

**Issue by mattispasch** [couchbase/couchbase-lite-java-javascript#2]
Hello,

when using a reduce function like

function(keys, values) {
   return sum(values);
}
or just "reduce" : "_sum"

the JavaScript-Compiler throws an exception because Reference "sum" is not defined.

I guess the sum functions are build-in functions in CouchDB and not plain JavaScript. 

I would be happy to see this fixed to be able to reuse (and replicate) design documents between CouchDB and Couchbaselite-Android.

**Comment by hideki** [comment]
Addressed by https://github.com/couchbase/couchbase-lite-java-javascript/pull/10
