### ISSUE TITLE
Using array.sort and array.reduce in a view.reduce

### ISSUE THREAD

**Issue by wanderanimrod** [couchbase/couchbase-lite-java-javascript#7]
Hi, we are trying to use sort and reduce array methods inside our reduce function in a view. We realise that these methods are not available on the javascript array object that is provided with the documents array in the views reduce function. Any ideas or ways that this could be accomplished?

**Comment by saubaer** [comment]
keys & values aren't "real" JavaScript Arrays.
You can fix that by using:
```javascript
function(keys, values, rereduce) {
keys = Array.prototype.slice.call(keys);
values = Array.prototype.slice.call(values);
// real JavaScript Arrays now
/* your reduce code */
}
```
Well ... a little late, but maybe it helps somebody.

**Comment by hideki** [comment]
Addressed by https://github.com/couchbase/couchbase-lite-java-javascript/pull/10
